### ISSUE TITLE
Ширина аватарки

### ISSUE THREAD

**Issue by NastasiaIva** [backuot/PageOfResume#13]
Внешнюю рамку аватарки задать через max-width, а не через явный width и добавить паддинг. Соответственно внутреннему элементу сделать ширину и высоту через 100% и убрать лишние свойства.
!!! В явном виде ширину и высоту задавать - дурной тон.

**Comment by backuot** [comment]
А каким должен быть родительский блок? К примеру если поместить автарку в блок main, сделать его инлайно-блочным, то внутренний элемент аватарки не будет вытягиваться на всю ширину внешнего.
