### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by kdenru** [backuot/PageOfResume#50]
Расхождение с макетом порядка 20px

**Comment by backuot** [comment]
А можно скриншот расхождения?

**Comment by kdenru** [comment]
![screenshot from 2016-11-03 15-33-30](https://cloud.githubusercontent.com/assets/16227419/19959674/f69ef01a-a1da-11e6-96b2-3520903591eb.png)

**Comment by kdenru** [comment]
![screenshot from 2016-11-03 15-44-57](https://cloud.githubusercontent.com/assets/16227419/19959998/cf3605c0-a1dc-11e6-870b-865a11d8ec57.png)
Если уменьшить ширину видимой области, то становится заметно расхождение по вертикали.
У тебя все сходится? Если да, то при каком размере окна?

**Comment by backuot** [comment]
![default](https://cloud.githubusercontent.com/assets/20247537/19960256/486efc34-a1de-11e6-969d-d1fc6bcb0166.png)
У меня ноутбук 1366х768px выглядит вот так, расхождение не большое

**Comment by kdenru** [comment]
Возможно у нас разные png-хи, которые открыты в pixelperfect. Отправь мне свою, по которой ты сверяешь.

**Comment by backuot** [comment]
![resume](https://cloud.githubusercontent.com/assets/20247537/19960492/ce53b870-a1df-11e6-8d56-2583352c35e6.png)

**Comment by kdenru** [comment]
С этим макетом вроде более-менее нормально сходится. Ок, тогда этот issue закрываем )

**Comment by backuot** [comment]
Давай я тогда и страницу с формой скину?)
