### ISSUE TITLE
Resume-head

### ISSUE THREAD

**Issue by kdenru** [backuot/PageOfResume#54]
Изображения лучше разнести по тем компонентам, где они используются и передавать в resume-head путь до них, а не подбирать их по названию класса, переданного из родительской компоненты

**Comment by backuot** [comment]
А можно конкретный пример, что куда передавать - не понятно.

**Comment by kdenru** [comment]
в миксин resume-head добавить еще один аргумент, в котором будет передаваться путь до изображения. https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_7ffv2/ (немного пролистай вниз, там в вопросе который начинается с "Всем привет. Нужна помощь" все расписано)
